#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "→ husky (commit-msg)"

if [ $(bun -v) ]; then
   bun commitlint --edit $1
elif [ $(bunx -v) ]; then
   bunx commitlint --edit $1
else
   echo "❌ This project use (bun|bunx)."
fi
