name: Code Formatter
on:
    workflow_dispatch:
    push:
        paths-ignore:
            - ".github/**"
            - ".husky/**"
            - "*.ttf"
            - "*.mp4"
            - "*.webm"

jobs:
    format:
        name: Code Formatting
        if: ${{ github.actor != 'renovate[bot]' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ vars.BUN_VERSION }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}

            - name: Install Dependencies
              run: bun install --ignore-scripts

            - name: Run ESLint
              run: bun run fix

            - name: Run Prettier
              run: bun run prettier

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore: code formatting"
                  skip_checkout: true
