name: Test
on: [workflow_dispatch, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/package.json', '**/bun.lockb') }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ vars.BUN_VERSION }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.NODE_VERSION }}

            - name: Install Dependencies
              run: bun install --verbose

            - name: Run ESLint
              run: bun run lint
