name: Test
on: [workflow_dispatch, pull_request]

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ vars.BUN_VERSION }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}

            - name: Install Dependencies
              run: bun install --ignore-scripts && bun install

            - name: Run ESLint
              run: bun run lint
